### PR TITLE
Fix Derp

### PR DESCRIPTION
**Pull request by aryanne99**

### CODE REVIEW

**Comment by synt4x93** [comment]
i really should start sleeping

**Comment by aryanne99** [comment]
Yeah , take some sleep, It's bad for health not to sleep.. Btw I'm Zoira at XDA ^^ .

**Comment by synt4x93** [comment]
Soon haha, rebased trees all my old branches are now called lineage-17.1-synt4x93

**Comment by synt4x93** [comment]
Soon haha, rebased trees all my old branches are now called "lineage-17.1-synt4x93"

New tree is enforcing and stock Q vendor is required, there may be some issues with sdcard exfat, fat32 works but will get this sorted.
(exfat works in permissive) if you want to boot permissive just use the "lineage-17.1-permissive" 
universal kernel branch

**Pull request merged**
